### PR TITLE
Prepare for v2.1.3 release

### PR DESCRIPTION
**Pull request by titodalcanton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by titodalcanton** [comment]
@conda-forge-admin, please rerender

**Comment by titodalcanton** [comment]
The OSX tests are failing presumably because of the problem which we started to fix in https://github.com/conda-forge/pycbc-feedstock/pull/74, and later fixed upstream instead. So what do we do here:
1. Scrap 2.1.3 and release 2.1.4 with that fix (functionally useless for PyCBC Live, purely to make OSX tests pass).
2. Ignore the OSX tests (I like this!)
3. Bring back some form of #74 here.

**Comment by duncanmmacleod** [comment]
@titodalcanton, if my vote is counted, I am in favour of Option 1.

However, if a new release is a large pain, and this error only manifests in conda, then it would be relatively easy to backport gwastro/pycbc#4353 as a [patch](https://patch-diff.githubusercontent.com/raw/gwastro/pycbc/pull/4353.patch). Let's call this Option 1b.

**Comment by titodalcanton** [comment]
I think option 1 is cleaner and overall less work than 1b, so I will go with that.

**Pull request closed without merging**
