### PR TITLE
Prepare for v2.1.2 release

### PR DESCRIPTION
**Pull request by titodalcanton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by titodalcanton** [comment]
@duncanmmacleod as far as I can tell, this is ready for approval. Not sure what to do about the failing action.

**Comment by duncanmmacleod** [comment]
@titodalcanton, did you attempt to rerender the feedstock (as per the checklist)?

**Comment by titodalcanton** [comment]
@conda-forge-admin please rerender

**Comment by titodalcanton** [comment]
@conda-forge-admin, please rerender

**Comment by titodalcanton** [comment]
Not sure where to post this, but here is a simple test case that triggers the same error:
```
(pycbc-dev) [tito@newman ~/debug_symbol_not_found]% cat test3.py 
import ctypes

ctypes.CDLL(
    '/Users/tito/miniconda3/envs/pycbc-dev/lib/libgomp.dylib',
    mode=ctypes.DEFAULT_MODE
)

import lalsimulation
(pycbc-dev) [tito@newman ~/debug_symbol_not_found]% python test3.py
Traceback (most recent call last):
  File "/Users/tito/debug_symbol_not_found/test3.py", line 8, in <module>
    import lalsimulation
  File "/Users/tito/miniconda3/envs/pycbc-dev/lib/python3.11/site-packages/lalsimulation/__init__.py", line 2, in <module>
    from .lalsimulation import *
  File "/Users/tito/miniconda3/envs/pycbc-dev/lib/python3.11/site-packages/lalsimulation/lalsimulation.py", line 12, in <module>
    from ._lalsimulation import *
ImportError: dlopen(/Users/tito/miniconda3/envs/pycbc-dev/lib/python3.11/site-packages/lalsimulation/_lalsimulation.so, 0x0002): symbol not found in flat namespace '___kmpc_flush'
```

**Comment by duncanmmacleod** [comment]
@titodalcanton, what happens if you change the `mode` to `ctypes.RTLD_LOCAL`?

**Comment by titodalcanton** [comment]
@duncanmmacleod no change, same error.

**Comment by titodalcanton** [comment]
@duncanmmacleod if we go ahead and merge this, will the package be released at least for Linux?

**Comment by duncanmmacleod** [comment]
I really would rather not merge failing builds. There are (were) a few different options to address the failing build.

**Pull request merged**
